plugin: amazon.aws.aws_ec2
aws_profile: default
regions:
  - "us-east-1" 
filters:
  instance-state-name : running

keyed_groups:
  - key: tags.Name

compose:
  ansible_host: public_ip_address



